<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SftpNetDrive</AssemblyName>
    <RootNamespace>SftpNetDrive</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x64;ARM64</Platforms>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Optimize>true</Optimize>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DokanNet" Version="2.2.1" />
    <PackageReference Include="SSH.NET" Version="2024.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\app.ico" Condition="Exists('Resources\app.ico')" />
  </ItemGroup>

</Project>
